# This file is generated via scripts/update_dependabot_yml.py. Do not update by hand.

# See the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Note: Dependabot only updates provider version if a lockfile is present. No lockfile, no update. We should
# always have a lockfile present, but if it's missing, at least now you know why dependabot didn't update it.

version: 2
updates:
  # directories in partition dev, chunk 1
  - package-ecosystem: "terraform"
    directories:
      - "/terraform/org-manager/tf-cost-alerts"
      - "/terraform/org-manager/tf-cost-reporting"
      - "/terraform/org-manager/tf-org-scp"
      - "/terraform/org-manager/tf-tfc-global-resources"
      - "/terraform/overwatch-prod/tf-tfc-global-resources"
      - "/terraform/prod/tf-bk-cluster-default-docker-build"
      - "/terraform/prod/tf-bk-cluster-infra-dr"
      - "/terraform/prod/tf-bk-cluster-testing"
      - "/terraform/prod/tf-misc-billing"
      - "/terraform/prod/tf-misc-data-eng"
      - "/terraform/prod/tf-misc-regeneron-printing"
      - "/terraform/prod/tf-misc-sightglass-ecr"
      - "/terraform/prod/tf-tfc-global-resources"
      - "/terraform/product-global-prod/tf-tfc-global-resources"
      - "/terraform/security-dev/tf-terraform-cloud-agent-pool"
    # this groups updates into a single PR encompassing all the above directories, with many providers upgraded per PR
    groups:
      terraform:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    allow:
      - dependency-name: "hashicorp/aws"
      - dependency-name: "hashicorp/tfe"
    reviewers:
      - "benchling/infra-foundational"
      - "cmonaghan"
      - "cmachine"
      - "bryan-benchling"
      - "bneutra"
    commit-message:
      prefix: "eng: (misc) "
    schedule:
      interval: "monthly"
      time: "01:00"
    labels:
      - "dependencies"
      - "prod"
